version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/package.json:/usr/src/app/package.json
      - ./frontend/yarn.lock:/usr/src/app/yarn.lock
    environment:
      - REACT_APP_API_URL=http://backend:5001
    depends_on:
      - backend

